### ISSUE TITLE
请问args的json数组参数有什么特殊要求？

### ISSUE THREAD

**Issue by Dearkano** [nebulasio/wiki#103]
"args":"{[\\"name\\":\\"abc\\",\\"age\\":\\"13\\"}]"这种提交以后会一直提示status是0
样例里只给了 [0]这种一个参数或者""没有参数的情况 希望demo能多讲一些

**Comment by smalloneSAMA** [comment]
兄弟，请问你是怎么进入console的 教程里没有说 然后我就直接 ./neb console 了 进去后教程的查询用户信息 查不了 说没有定义那些标识符。。。。  比如例子 curl ....'{" 账户地址"}'   我的报错 unexpected  identifier

**Comment by Dearkano** [comment]
@smalloneSAMA  不用进console的 网络启动以后在文件夹目录下直接curl 或者远程http调用 无所谓的

**Comment by smalloneSAMA** [comment]
恩 谢谢了

**Comment by ChengOrangeJu** [comment]
@Dearkano 返回值的status是0时表示你的transaction执行失败了。请问是否是别的原因导致的？比如nonce, gasprice, gaslimit的错误。官方后续会提供更多的样例：）

**Comment by Dearkano** [comment]
@ChengOrangeJu  谢谢回复 nonce错误的话tx都不会发成功的，所以应该不是 price和limit都是使用了默认数值，所以应该是没问题的，我想到的问题就是args参数（demo也是这么说的），所以比较想问问args的json数组是什么格式的 我1L所写的格式是否有问题？

**Comment by ChengOrangeJu** [comment]
@Dearkano 额，貌似你贴的那个里面大括号和中括号匹配不上啊

**Comment by ChengOrangeJu** [comment]
args: {"function":"save","args":"[\"测试急死啦\",\"没用的\"]"}

**Comment by Dearkano** [comment]
@ChengOrangeJu  感谢回复 1L的括号是打错了 debug发现我的问题是在于对args做了json parse（看节点log发现的） 但是发现在转义引号的时候还是有问题 另开issue了[]https://github.com/nebulasio/wiki/issues/108)
