### ISSUE TITLE
"error":"invalid character '\\\\' looking for beginning of value"

### ISSUE THREAD

**Issue by Dearkano** [nebulasio/wiki#108]
在进行智能合约储存区键值对储存测试时，进行query遇到"error":"invalid character '\\\\' looking for beginning of value"的错误提示

代码如下

 save: function (jsonstr) {
        this.redisdb.put("test", jsonstr);
        },
 query: function () {
        var x = this.resumedb.get("test");
        return x;
  }

调用save时成功 status=1
但query时报错

查询语句
curl -i -H 'Accept: application/json' -X POST http://localhost:8685/v1/user/call -H 'Content-Type: application/json' -d '\{"from":"n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE","to":"n1tL2fXV7Eh1sonkqBxc8hGUkMsQhJMq7cm", "value":"0","nonce":28,"gasPrice":"1000000","gasLimit":"2000000","contract":{"function":"query","args":""}}'

因为合约部署时引号都进行了转义 怀疑可能这里出了问题

**Comment by Dearkano** [comment]
同时还想问js编写合约时能否使用类似console.log 输出一些日志便于调试

**Comment by Dearkano** [comment]
已解决

**Comment by harryge00** [comment]
@Dearkano console.log 在哪里能看到呢？
