### ISSUE TITLE
文档有些问题

### ISSUE THREAD

**Issue by lucky917** [nebulasio/wiki#110]
Nebulas 101 - 04 智能合约存储区.md中
![image](https://user-images.githubusercontent.com/12198768/39773656-53369654-532b-11e8-98b8-4ff5dc16e9af.png)
其中红色部分 按照上下文理解 应该是defineProperty 而不是defineMapProperty吧

**Comment by jianhuaixie** [comment]
文档到处都是粗心大意的问题，https://github.com/nebulasio/wiki/blob/master/permission_control_in_smart_contract.md

**Comment by ChengOrangeJu** [comment]
Hello @jianhuaixie We are looking into the document issue and will update soon. Thanks for the information.

**Comment by BrushXiaoMinGuo** [comment]
@lucky917 
![39773656-53369654-532b-11e8-98b8-4ff5dc16e9af](https://user-images.githubusercontent.com/7351297/39817091-c4fe046c-53cf-11e8-9edb-d1da43343be3.png)
defineMapProperty中`descriptor`设置为null，将使用默认的JSON.stringify()和JSON.parse()；也可以定义实现`descriptor`。红色部分是设置为null的用法。

**Comment by BrushXiaoMinGuo** [comment]
Hello @jianhuaixie we have updated the document ,Thanks for the information.
