### ISSUE TITLE
服务器不支持OPTIONS请求

### ISSUE THREAD

**Issue by Dearkano** [nebulasio/wiki#111]
开放端口使用curl或者远程用chrome的rest http插件调用都没问题 跨域也没问题
但是浏览器实现的时候发送fetch请求，预检OPTIONS挂了，501 not implemented 服务器不支持OPTIONS请求，想了想这个是不是nebulas本身不支持呢？

**Comment by ChengOrangeJu** [comment]
rpc {
    rpc_listen: ["0.0.0.0:8684"]
    http_listen: ["0.0.0.0:8685"]
    http_module: ["api","admin"]
    # HTTP CORS allowed origins
    http_cors: ["*"]
}

add http_cors:["*"] in your default config.
OPTIONS method is not supported

**Comment by ChengOrangeJu** [comment]
1. leave only the first dynasty in conf/default/genesis.conf
```
for example:

     dynasty: [
        "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
     ]
```

2. enable start_mine  and set miner & coinbase in conf/default/config.conf
```
diff --git a/conf/default/config.conf b/conf/default/config.conf
index 15b310ce..92f205be 100644
--- a/conf/default/config.conf
+++ b/conf/default/config.conf
@@ -12,7 +12,11 @@ chain {
   datadir: "data.db"
   keydir: "keydir"
   genesis: "conf/default/genesis.conf"
-  start_mine: false
+  start_mine: true
+  miner: "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
+  coinbase: "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
+  passphrase: "passphrase"
   signature_ciphers: ["ECC_SECP256K1"]
 }
```
3. perhaps you need to enable cross domain to make local testing easier
```
rpc {
rpc_listen: ["0.0.0.0:8684"]
http_listen: ["0.0.0.0:8685"]
http_module: ["api","admin"]
# HTTP CORS allowed origins
+ http_cors: ["*"]
}
```
