### ISSUE TITLE
Makefile:66: recipe for target 'build' failed make: *** [build] Error 1

### ISSUE THREAD

**Issue by bd506723144** [nebulasio/wiki#117]
**Makefile:66: recipe for target 'build' failed
make: *** [build] Error 1**
这个有人遇到么，最后一步 make build的时候

Makefile 66行是和 shared_lib 有关的代码

**Comment by ChengOrangeJu** [comment]
Hello @bd506723144 check this issue https://www.reddit.com/r/nasdev/comments/8gsoqc/installing_nebulas_on_ubuntu/
 maybe you have similar issue
