### ISSUE TITLE
启动星云节点有问题！

### ISSUE THREAD

**Issue by anlian310** [nebulasio/wiki#120]
make build成功之后，启动第一个节点./neb -c conf/default/config.conf，启动后一直没有结束，必须ctrl+c才能终止命令，结果如下
![image](https://user-images.githubusercontent.com/39152898/39860919-9bd25b2c-5471-11e8-949f-770be7414a9e.png)

CTRL+c后的情况如下：
![image](https://user-images.githubusercontent.com/39152898/39861207-777d4d94-5472-11e8-9a2d-9e2718fd7afc.png)

再启动挖矿节点./neb -c conf/example/miner.conf，也是同样的问题，不能连接seed节点实现同步：
![image](https://user-images.githubusercontent.com/39152898/39861068-01c9e8c8-5472-11e8-8904-1b83192240a8.png)

请教大家这是什么问题？如何解决？

**Comment by ChengOrangeJu** [comment]
@anlian310 Maybe you could check https://github.com/nebulasio/go-nebulas/issues/109 for how to start your private chain
