### ISSUE TITLE
官方 js 例子无法通过 deploy 的 test

### ISSUE THREAD

**Issue by leyle** [nebulasio/wiki#121]
https://github.com/nebulasio/wiki/blob/master/tutorials/%5B%E4%B8%AD%E6%96%87%5D%20Nebulas%20101%20-%2003%20%E7%BC%96%E5%86%99%E6%99%BA%E8%83%BD%E5%90%88%E7%BA%A6.md

这里的例子，在测试网 deploy 时，点击 test 报错 。

{"result":"\"\"","execute_err":"","estimate_gas":"22711"}

**Comment by ChengOrangeJu** [comment]
execute_err":"" means no error
