### ISSUE TITLE
Mac  make build  报错

### ISSUE THREAD

**Issue by 0o8o0** [nebulasio/wiki#123]
`cd cmd/neb; go build -ldflags "-X main.version=1.0.1 -X main.commit=ce7e09897df516f5877fb4ed209cf5f42d244b55 -X main.branch=master -X main.compileAt=`date +%s`" -o ../../neb-ce7e09897df516f5877fb4ed209cf5f42d244b55
accountcmd.go:25:2: cannot find package "github.com/nebulasio/go-nebulas/cmd/console" in any of:
	/usr/local/Cellar/go/1.10.2/libexec/src/github.com/nebulasio/go-nebulas/cmd/console (from $GOROOT)
	/Users/qt/go/src/github.com/nebulasio/go-nebulas/cmd/console (from $GOPATH)
`
求解

**Comment by ChengOrangeJu** [comment]
@0o8o0 Check this issue, it contains so many errors that build might encounters https://www.reddit.com/r/nasdev/comments/8gsoqc/installing_nebulas_on_ubuntu/

**Comment by 0o8o0** [comment]
@ChengOrangeJu I tried that, but it does'n work.
`chown: artur: illegal group name`

**Comment by ChengOrangeJu** [comment]
@0o8o0 
(1) double check your Gopath
(2) if you use chown, please use your group name, for example 0o8o0. artur is another people
