### ISSUE TITLE
传递参数时，是否支持列表传入？

### ISSUE THREAD

**Issue by leyle** [nebulasio/wiki#134]
比如 
["args1", "args2", "[\"l1\", \"l2\"]", "args4"]

**Comment by smartpunter** [comment]
You can pass any valid javascript data.
calling method testMethod with params ["args1", "args2", ["l1", "l2"], "args4"]

testMethod = function (arg1, arg2, arg3, arg4){
  // Here arg3[1] === "l2"
}

**Comment by yupnano** [comment]
the argument should be a JSON string of args array, you can use `JSON.stringify`  to generate a string as your argument.
Take your `["args1", "args2", "["l1", "l2"]", "args4"]` as an example:
![qq 20180513024328](https://user-images.githubusercontent.com/5012612/39960555-75dd446c-5657-11e8-868b-18281115faf3.png)
