### ISSUE TITLE
payId does not exist

### ISSUE THREAD

**Issue by NexusLee** [nebulasio/wiki#138]
调用 nebPay.queryPayInfo 时 testnet 返回 code 0，切换到 mainnet 时， 一直报 payId does not exist， 可能是什么问题

**Comment by yupnano** [comment]
queryPayInfo 默认是在测试网查询交易结果，现在改为默认在主网查询了。如果要在测试网查询，可以把options.callback 参数指定为测试网的查询服务器 [`callback: NebPay.config.testnetUrl`](https://github.com/nebulasio/nebPay/blob/master/doc/NebPay%E4%BB%8B%E7%BB%8D.md#options)

**Comment by NexusLee** [comment]
@yupnano 切换到最新版本解决了
