### ISSUE TITLE
获取合约内所有数据的方法

### ISSUE THREAD

**Issue by 0o8o0** [nebulasio/wiki#142]
有获取合约内所有内容的方法吗？
比如有一个get方法可以根据num属性get(num)查找相关数据，怎么获取所有的数据呢？

**Comment by yupnano** [comment]
这个需要自己实现，可以参考tutorial中的[Map数据遍历](https://github.com/nebulasio/wiki/blob/master/tutorials/%5B%E4%B8%AD%E6%96%87%5D%20Nebulas%20101%20-%2004%20%E6%99%BA%E8%83%BD%E5%90%88%E7%BA%A6%E5%AD%98%E5%82%A8%E5%8C%BA.md#map%E6%95%B0%E6%8D%AE%E9%81%8D%E5%8E%86)，用两个map实现类似数组的功能，分别定义map(index,key)和map(key,value)，这样可以实现map中数据的遍历。

**Comment by 0o8o0** [comment]
@yupnano 谢谢，已经解决了。
