### ISSUE TITLE
测试网络没法储存数据啊

### ISSUE THREAD

**Issue by dbsGen** [nebulasio/wiki#143]
'use strict';
      function OpenMarket() {
      }

      OpenMarket.prototype = {
          init: function () {
          },
          get_id: function () {
              return LocalContractStorage.get('key1');
          },
          set_id: function (val) {
              return LocalContractStorage.set('key1', val);
          }
      };
      module.exports = OpenMarket;

我就用web钱包里面的执行来测试，结果设置的时候是返回的0，获得的时候返回null。

**Comment by 0o8o0** [comment]
源码运行
你set_id执行完后过一段时间再执行get_id就可以看到了，它只是比较慢

**Comment by act262** [comment]
部署、执行合约代码都要等待一段时间后才有效

**Comment by yupnano** [comment]
是不是 set_id 的时候用的"测试"按钮，没有点“提交”？
测试只是模拟执行结果，并不会发送交易，执行结果不会上链。这时候 get_id 肯定是null了。
