### ISSUE TITLE
发送交易失败 account is not found

### ISSUE THREAD

**Issue by flute** [nebulasio/wiki#162]
发送交易三种方式：

- 签名 & 发送
- 密码 & 发送
- 解锁 & 发送

使用第1、2种方式发送交易失败。原因：调用接口创建了账号，但未将keystore存在指定路径。

问题一：
第2、3种方式文档明确指出，需要上传keystore文件至节点目录，第一种没有说明，那么第一种是否需要？

问题二：
将keytore存在其他路径，或以字符串形式存在数据库时。如何实现交易？

**Comment by farmerljx** [comment]
在本地签名要怎么做,加入testnet和mainnet的文档看不是很懂,需要本地起一个节点吗?还是怎么样?

**Comment by flute** [comment]
1、第一种不需要在节点目录存储keystore.
2、参考neb.js文档
