### ISSUE TITLE
【Installation Error】executing when make dep by following official wiki

### ISSUE THREAD

**Issue by flashdoggy** [nebulasio/wiki#173]
```
*@*:/usr/local/go/work/src/github.com/nebulasio/go-nebulas# sudo make dep

dep ensure -v

make: execvp: dep: Permission denied

make: *** [dep] Error 127
```

As above, after I following by [this step](https://github.com/nebulasio/wiki/blob/master/tutorials/%5B%E4%B8%AD%E6%96%87%5D%20Nebulas%20101%20-%2001%20%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85.md#%E4%B8%8B%E8%BD%BDgo%E4%B8%89%E6%96%B9%E5%BA%93)

Even if I tried given a permission by using chmod 755 on that folder, that didnt work.

Here is my OS info:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
and, I'm following the steps from the beginning.

I'm not sure how this showed. 

plz anyone can help, thx first

**Comment by flashdoggy** [comment]
Alright, in fact, I was not noticing the following message after that.
coz that asked to wget a taz file, after I get that, there is no need to get a making process.
but just in case, a little bit curious.

**Comment by yupnano** [comment]
This error seems resolved by yourself, then I will close this issue,
