### ISSUE TITLE
config.conf应该怎么配置帐号密码，白名单，walletnotify等这些参数呢？

### ISSUE THREAD

**Issue by boy-good** [nebulasio/wiki#178]
请问启动节点时的config.conf应该怎么配置帐号密码，白名单，walletnotify等这些参数呢？？？

**Comment by ChengOrangeJu** [comment]
账号密码的初始金额在genesis.conf里面配置。
白名单具体指的什么呢？Http_cors?

**Comment by boy-good** [comment]
白名单就是具有访问该节点权限的ip呀。

**Comment by ChengOrangeJu** [comment]
目前没有这个配置
