### ISSUE TITLE
主网节点后台运行问题

### ISSUE THREAD

**Issue by flute** [nebulasio/wiki#181]
主网节点如何在后台稳定运行，进程守护最佳实践？能否给出官方示例。

**Comment by LeonLi000** [comment]
官方是使用[supervisor](http://supervisord.org/)来管理neb进程

> [program:neb]
directory=/neb/app
user=app
command=/neb/app/neb -c /neb/app/conf/config.conf
stdout_logfile=/neb/app/logs/out.log
stderr_logfile=/neb/app/logs/err.log
autostart=true
autorestart=true

**Comment by flute** [comment]
OK，tks, 使用systemd出现了一些问题，换成supervisor暂无问题。
