### ISSUE TITLE
白皮书中 go 版本不一致

### ISSUE THREAD

**Issue by ruoqianfengshao** [nebulasio/wiki#2]
推荐使用 go@1.8以上，文档示例却是1.7.6，是否应该保持一致，或使用最新的版本？
![image](https://user-images.githubusercontent.com/2928664/34025290-0031f70e-e18a-11e7-8483-4354204170be.png)

**Comment by qywang2012** [comment]
使用最新版本就可以，最低要求是`>=1.8`,教程中的~/.bash_profile是给的示例，具体以安装的版本为准。稍后会更新教程的文档。

**Comment by qywang2012** [comment]
https://github.com/nebulasio/wiki/blob/master/tutorials/%5B%E4%B8%AD%E6%96%87%5D%20Nebulas%20101%20-%2001%20%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85.md
文档已更新
