### ISSUE TITLE
GetTransactionReceipt 返回值过长会被截取。

### ISSUE THREAD

**Issue by antgan** [nebulasio/wiki#200]
如题，前几天遇到的问题，忘记截图了。调用该接口，返回值如果过长，最后会被截取掉。
希望官方修复

**Comment by yupnano** [comment]
是的，GetTransactionReceipt  返回结果中的 "execute_result" 做了限制，最大允许255字节。如需更长的返回值，请调用Call。

**Comment by antgan** [comment]
明白！那上链的速度是如何计算的呢。现在Mainnet和testnet  pending很久。跟GasLimit和Price有关吗

**Comment by yupnano** [comment]
很可能是交易参数不合适，导致无法上链，最终会执行错误。比如nonce太大，gasPrice、GasLimit过低。
可以发一下txhash吗？

**Comment by antgan** [comment]
016074373ef62e3caf8887ee86ae1374042379d3de813fdb741bf7c9dd930bfe

**Comment by antgan** [comment]
Mainnet

**Comment by antgan** [comment]
噢，我账户没NAS，Mainnet解决了。那testnet很不稳定，经常Timeout  怎么解决呢
