### ISSUE TITLE
Questions for Clarity

### ISSUE THREAD

**Issue by Anoteros** [nebulasio/wiki#22]
Hi,

Love the project. Just trying to get TestNet configured properly and wanted a bit more clarity on the setup:

1. Does the Token claim at https://testnet.nebulas.io/claim/ require me to run ./neb every day for tthe 10 NAS Testnet Tokens?
2. Will the TestNet Tokens become real NAS Tokens? Before or after Mainnet launch?

**For the config ./neb**

1. Which addresses in the config files do I need to swap out for my own? Do I want to include my testnet wallet address or just a coinbase address? For coinbase, should it be the ETH address?
2. I guess it is just not clear enough to me which information I should be swapping out for my own. 

> # NAS dispatch，
> token_distribution [
>   {
>     address: "1a263547d167c74cf4b8f9166cfa244de0481c514a45aa2c"
>     value: "10000000000000000000000"
>   },
>   {
>     address: "2fe3f9f51f9a05dd5f7c5329127f7c917917149b4e16b0b8"
>     value: "10000000000000000000000"
>   }
> ]

>   # Mining machine's mining address, the reward will be send to a Coinbase address
>   coinbase: "eb31ad2d8a89a0ca6935c308d5425730430bc2d63f2573b8"
>   # Node signature algorithm
>   signature_ciphers: ["ECC_SECP256K1"]
>   # Mining machine's mining address
>   miner: "eb31ad2d8a89a0ca6935c308d5425730430bc2d63f2573b8"

> # Initial Token Distribution is described here
> token_distribution [
>   {
>     address: "0b9cd051a6d7129ab44b17833c63fe4abead40c3714cde6d"
>     value: "10000000000000000000000000"
>   },
>   {
>     address: "4aa6312b10dd81f68eb62a90e234a48eb83c6b0e568b5eb8"
>     value: "10000000000000000000000000"
>   }
> ]

Love the project, just want to help. Thanks in advance.

**Comment by Anoteros** [comment]
Do I just mine to my Coinbase ETH address? Or do I use the Coinbase generated address in the tutorial?

Also getting an error during: https://github.com/nebulasio/wiki/blob/master/tutorials/%5BEnglish%5D%20Nebulas%20101%20-%2002%20Transaction.md

`curl -i -H 'Accept: application/json' -X POST http://localhost:8685/v1/user/transaction -H 'Content-Type: application/json' -d '{"from":"1a263547d167c74cf4b8f9166cfa244de0481c514a45aa2c","to":"bf9f8c6d12797d44ea5213988aaad87e964eef32e4fab0dd","nonce": 1,"value": “10”}'
`

`{"error":"invalid character 'â' looking for beginning of value","code":3}`

**Comment by qywang2012** [comment]
@Anoteros 

1. The Token claim at https://testnet.nebulas.io/claim/ didn't require run neb;
2. Testnet tokens only used for developers do test transactions,  can not become real NAS Tokens;

For Testnet
you needn't change the config's coinbase and miner address, as the Testnet use dpos and you cann't mine currently. You only need to update you seed configuration.

For you private net
the gengesis conf may give you nas and you can change the miner and coinbase

**Comment by Anoteros** [comment]
@qywang2012 Thank you for the reply. 

> For you private net
> the genesis conf may give you nas and you can change the miner and coinbase.

Which address do I put for miner and coinbase? My coinbase eth address? Or MEW wallet?

**Comment by qywang2012** [comment]
use `./neb account new` to generate new address. Nebulas address not equal to eth address.

**Comment by Anoteros** [comment]
@qywang2012 

Ok. I am using the address ` ./neb account new` gave me as the miner and coinbase address. I will mine NAS token to this address? Do I get to keep it?

Thank you for your help :)

**Comment by qywang2012** [comment]
you mine nas token to your coinbase address. The miner unlocked with the passphrase in config.conf and mine the block, the reward give to coinbase address.

**Comment by Anoteros** [comment]
Where do I find my coinbase address? `./neb account new` ?

Sorry for trouble.

**Comment by qywang2012** [comment]
`./neb account new` just generate a new address, you can set the address as the coinbase and miner address.

**Comment by Anoteros** [comment]
Ok thank you!

**Comment by patnebulas** [comment]
Hi,

@qywang2012 : Thank you for all the explanation.

I would have one question : when you said : "Testnet tokens only used for developers do test transactions, can not become real NAS Tokens"
mean right now even if we are using ./neb we will not have real token ?
Also when I claim token with my email address and the address I have always 0, is it normal ? 

Many thanks in advance

**Comment by qywang2012** [comment]
@patnebulas 
The Testnet just for developer testing, so the token is not the real token.Just like eth on the ethereum test network.
you should check the address is valid and generated by nebulas.
