### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Olovorr** [nebulasio/wiki#23]
Hi!

So I followed steps described in [installation tutorial](https://github.com/nebulasio/wiki/blob/master/tutorials/%5BEnglish%5D%20Nebulas%20101%20-%2001%20Installation.md), however I am unable to run make build.

When I run `make build`, it gives me following response:

<img width="1400" alt="screen shot 2018-01-07 at 20 49 15" src="https://user-images.githubusercontent.com/15366622/34653455-44994cd4-f3ec-11e7-879a-a6287452bfa9.png">

Any ideas how to solve this issue? Sorry if it is a dumb question, I don't have a whole lot experience with GO.

Thanks!

**Comment by patnebulas** [comment]
Hi,

I have the same issue, when I execute make build I have this errors: 
cd cmd/neb; go build -ldflags "-X main.version=0.6.0 -X main.commit=a5ead6d389afae736e2b876020e5a9acc4fdc1ec -X main.branch=develop -X main.compileAt=`date +%s`" -o ../../neb
# github.com/go-nebulas/cmd/neb
./crashclient.go:41:3: undefined: logging.CLog
./crashclient.go:61:3: undefined: logging.CLog
./crashclient.go:79:7: conf.CrashReportUrl undefined (type *nebletpb.AppConfig has no field or method CrashReportUrl)
./crashclient.go:83:3: undefined: logging.CLog
./crashclient.go:91:3: undefined: logging.CLog
./crashclient.go:110:3: undefined: logging.CLog
./crashclient.go:117:2: undefined: logging.CLog
./main.go:85:2: undefined: logging.Init
./main.go:88:59: n.Config().App.CrashReportUrl undefined (type *nebletpb.AppConfig has no field or method CrashReportUrl)
./main.go:123:10: conf.App.Version undefined (type *nebletpb.AppConfig has no field or method Version)
./main.go:123:10: too many errors
make: *** [build] Error 2

**Comment by qywang2012** [comment]
Please use the master branch code. The develop branch has changed and not released. The tutorials are released for v0.5.0 on master branch

**Comment by Olovorr** [comment]
Thanks for the answer, it works now! 

However, maybe it would be a good idea to mention it in the tutorial here - 
<img width="914" alt="screen shot 2018-01-08 at 09 54 46" src="https://user-images.githubusercontent.com/15366622/34664014-ff591a0a-f459-11e7-9fdc-a5a1768ebaf7.png">

Because I thought that the only difference between those two is that one is with commit history and other is not. I can make PR if you are too busy.

**Comment by qywang2012** [comment]
good! You can pull a request for the tutorial and update it.@Olovorr

**Comment by patnebulas** [comment]
Hi,

Many thanks for your quick answer, now it s work, I would have one last question.

I can t find seed.conf in the path you mention so I create it but where can I find the seed to put below: 
 # seed: "UNCOMMENT_AND_SET_SEED_NODE_ADDRESS"


Many thanks in advance
