### ISSUE TITLE
Can't find seed config file

### ISSUE THREAD

**Issue by Tester1988** [nebulasio/wiki#25]
Thank you for a great tutorial

I am stuck on the creation block configuration part of the tutorial
I can't seem to find the seed.conf file under the go-nebulas/conf/default.
I have the genesis.conf and config.conf files

Please advise what steps I may have missed.

Thank you

**Comment by qywang2012** [comment]
@Tester1988 
Sorry, I have updated the tutorial, our Testnet have updated the config and the tutorial is old. Just use the `conf/default/config.conf`.
https://github.com/nebulasio/wiki/blob/master/tutorials/%5BEnglish%5D%20Nebulas%20101%20-%2001%20Installation.md
