### ISSUE TITLE
参与测试，对代码进行make build时提示找不到对应的文件，这个huandun要单独下载吗？

### ISSUE THREAD

**Issue by xiarilian12** [nebulasio/wiki#37]
<img width="1372" alt="1112" src="https://user-images.githubusercontent.com/1791767/34943351-4cf757e0-fa36-11e7-8765-e1085911e93a.png">

运行 make build 错误如上图所示
我是从这里拉的代码
git clone https://github.com/nebulasio/go-nebulas.git
develop分支

**Comment by qywang2012** [comment]
@xiarilian12 
please use the master branch.  
`make dep` first to fetch dependency, then you can  `make build`.
Note: If `make dep` failed, you can download vendor.tar.gz, which told in [tutorial](https://github.com/nebulasio/wiki/blob/master/tutorials/%5B%E4%B8%AD%E6%96%87%5D%20Nebulas%20101%20-%2001%20%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85.md).
