### ISSUE TITLE
running ./neb error 

### ISSUE THREAD

**Issue by ottokafka** [nebulasio/wiki#55]
When installing Nebulas for the first time and running ./neb users will receive the error.

**Error**: err="the size of initial dynasty in genesis block is un-safe, should be greater than or equal 8" file=main.go func=main.runNeb line=109

![image](https://user-images.githubusercontent.com/21117852/36717622-b75e72fc-1bd9-11e8-967f-d4435ab2292f.png)

**The solution:**
Add more address to the Dynasty block or genesis.conf file. Example below 

![image](https://user-images.githubusercontent.com/21117852/36717738-2b58f204-1bda-11e8-9150-58dfc2b12735.png)

![image](https://user-images.githubusercontent.com/21117852/36717759-4d485ab2-1bda-11e8-8e7f-55d06c26fc4d.png)

This will fix the error above

**Comment by qywang2012** [comment]
For go-nebulas master branch, the dynasty size is 21, the default conf genesis dynasty is 6, less than 1/3 of the dynasty size 21, so it throws the error.
You can use the Testnet config for master branch `./neb  -c testnet/conf/config.conf`

**Comment by ottokafka** [comment]
ok issue solved don't use ./neb alone unless manually configuring genesis.conf. Users should always pointed toward testnest config.conf
