### ISSUE TITLE
How to upgrade or change my smart contract code

### ISSUE THREAD

**Issue by act262** [nebulasio/wiki#74]
Firstly deploy my code successfully, and then I need improve my code, so how can I change my smart contract?

**Comment by fbzhong** [comment]
Hi Act262,

In blockchain system, all data/state are immutable. That means we can't change data after on chain.

So if you want to update the smart contract code, you have to deploy the latest code and get a new contract address.

And we are working on the `Nebulas Force`, which provide `upgradability` to Nebulas. In that circumstances, developer could `upgrade`, not overwrite, their smart contract. 

Wish that would be helpful.
