### ISSUE TITLE
 make shared_lib && make install-shared报错

### ISSUE THREAD

**Issue by bochain** [nebulasio/wiki#83]
完全按照步骤执行，到这一步出现这个问题
 make shared_lib && make install-shared：
报错如下：
root@bochain:/path/to/workspace/src/github.com/nebulasio/go-nebulas# cd rocksdb & make shared_lib && make install-shared
[1] 524
make: *** No rule to make target 'shared_lib'.  Stop.
[1]+  Done

**Comment by bochain** [comment]
环境：ubuntu 16.04

**Comment by RickeeyZhou** [comment]
首先保证gcc 和 g++ 在4.7以上
gcc --version  
g++ --version  
 
安装必要的库
apt-get -y install build-essential  
apt-get -y install libsnappy-dev zlib1g-dev libbz2-dev  
 
下载rocksdb的源码
https://github.com/facebook/rocksdb/releases
rocksdb-4.1.tar.gz
 
or
git clone https://github.com/facebook/rocksdb.git  
cd rocksdb  
git checkout v4.1  
 
安装rocksdb
PORTABLE=1 make shared_lib  
INSTALL_PATH=/usr/local make install-shared  
 
设置环境变量
vim ~/.bashrc  
 
add
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:/blockchain/rocksdb/include  
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/blockchain/rocksdb  
export LIBRARY_PATH=${LIBRARY_PATH}:/blockchain/rocksdb  
 
source ~/.bashrc  
 
使用 python测试连接成功
apt-get –y install python-virtualenv python-dev  
virtualenv pyrocksdb_test  
pip install "Cython>=0.20"  
pip install git+git://github.com/stephan-hof/pyrocksdb.git  
 
root@ubuntu:/blockchain/pyrocksdb_test# python  
Python 2.7.12 (default, Nov 19 2016, 06:48:10)   
[GCC 5.4.0 20160609] on linux2  
Type "help", "copyright", "credits" or "license" for more information.  
>>> import rocksdb  
>>> db=rocksdb.DB("test.db",rocksdb.Options(create_if_missing=True))  
>>> db.put(b"key1",b"v1")  
>>> db.put(b"key2",b"v2")  
>>> db.get(b"key1")  
'v1'  
>>> db.get(b"key2")  
'v2'  
>>> del db  
>>> quit()  
root@ubuntu:/blockchain/pyrocksdb_test#
Ubuntu安装rocksdb4.1并使用pyrocksdb测试连接成功

**Comment by tendertime** [comment]
因为步骤就是错的 
wiki里这个句子是 cd rocksdb & make shared_lib && make install-shared
把第一个&改到&&就好了

**Comment by norsk76** [comment]
What worked for me was not using && and going step by step and using sudo for make install shared.
cd rocksab
make shared
sudo make install-shared

**Comment by bd506723144** [comment]
: make shared 
and
 : make install-shared

**Comment by ChengOrangeJu** [comment]
Hello @bochain sorry for the inconvenience, the wiki is updated. Thanks @tendertime

**Comment by bochain** [comment]
@RickeeyZhou @tendertime @norsk76 @bd506723144 @ChengOrangeJu  thanks for everyone ,The problem has been solved，thanks again !
