### ISSUE TITLE
LocalContractStorage Cannot set property!

### ISSUE THREAD

**Issue by xbhuang1994** [nebulasio/wiki#84]
`
var BankVaultContract = function () {
    LocalContractStorage.defineMapProperty(this, "userArray", null);
`
...
`
init: function () {
        this.userArray = [];
`
Test result:

{"result":"TypeError: Cannot set property userArray of #<Object> which has only a getter","execute_err":"Deploy: TypeError: Cannot set property userArray of #<Object> which has only a getter","estimate_gas":"25648"}

Where am I wrong?

**Comment by xbhuang1994** [comment]
I found the problem, you should use defineProperty instead of defineMapProperty

**Comment by ChengOrangeJu** [comment]
@xbhuang1994 Congrats!
