### ISSUE TITLE
Problem while downloading go third party lib

### ISSUE THREAD

**Issue by bjtu1133** [nebulasio/wiki#88]
I'm trying to follow the this guide to deploy Neblus on my machine, however I met an error while trying to downloading go third party lib. 
When I'm executing `sudo make dep`
Got an error:
`dep ensure -v
/path/to/workspace/src/github.com/nebulasio/go-nebulas is not within a known GOPATH/src
make: *** [dep] Error 1`

When I'm executing
`echo $GOPATH`
Result:
`/path/to/workspace`

Here is my GOPATH from go env
![image](https://user-images.githubusercontent.com/1168149/39674124-41d00f5c-5115-11e8-9ff2-e59d8fc81027.png)

I'm using a mac machine, and not very familiar with Go, so not sure if I'm filing the issue in the correct place. But I really need some help.

**Comment by bjtu1133** [comment]
Problem solved by exporting GOPATH by doing 
`export GOPATH=users/XXX/to/workspace`
It seems dep not working very well with 'sudo'.
I think it is better to update readme to give ppl an idea that this `path` is better to be some folder not require sudo. It may save some time for ppl who is not that familiar with Go.

**Comment by ChengOrangeJu** [comment]
@bjtu1133 Sure, your advice is precious
