### ISSUE TITLE
Some questions from beginner

### ISSUE THREAD

**Issue by momoko8443** [nebulasio/wiki#92]
Hi guys,
I'm a beginner of Nebulas, my friend invent me to join the 'incentive' plan, I've registered the account with his invent code, then I created my wallet on the Mainnet and try to deploy the contract, but I found that I haven't got any money (NAS) to pay this trade by GAS, so I thinks it's  impossible to join the game for me...
Could you tell me what can I do next step?

**Comment by ChengOrangeJu** [comment]
Try https://testnet.nebulas.io/claim/ to claim nas for you! Good luck

**Comment by ChengOrangeJu** [comment]
Hi @momoko8443 this is for testnet

**Comment by momoko8443** [comment]
hi, @ChengOrangeJu ，thx for your quick response. If I pass the testing on testnet ENV, then I wanna deploy contract to Mainnet, how can I get my first NAS to pay for the trade?

**Comment by momoko8443** [comment]
Hi @ChengOrangeJu, I request 10 NAS on the testnet about 30mins ago with the URL which you provided, but the testing NAS still not transfer to my account. Could you help to make a checking?

my email is "momoko8443@gmail.com"
my testnet wallet is "n1ZGraAU2Fw7XALmmFoftdRwTPP49RJNqCt"
