### ISSUE TITLE
启动挖矿节点,无法启动.显示有锁,如何解决

### ISSUE THREAD

**Issue by jiyilanzhou** [nebulasio/wiki#93]
Failed to open disk storage.                  dir=data.db err="IO error: While lock file: data.db/LOCK: Resource temporarily unavailable" file=main.go func=main.runNeb line=108
这个如何解决

**Comment by ChengOrangeJu** [comment]
Have you started a local node before? Could it be some sort of error with dir permission? 
Try to rm data.db/* (if there is no useful data ) or  sudo chown -R yourname:yourname go-nebulas

**Comment by jiyilanzhou** [comment]
节点已经启动了,挖矿节点早上可以挖矿.我刚才把data.da删除了,miner.1.db.也删除了.重新执行还是不行.
我早上可以挖矿,应该不是权限问题.
执行的命令是./neb conf/example/miner.conf

**Comment by jiyilanzhou** [comment]
有开发者群吗,问题一直得不到解决

**Comment by ChengOrangeJu** [comment]
@jiyilanzhou I checked the code, it happened when try to new a rocksdbstorage.

**Comment by jiyilanzhou** [comment]
我checkout掉了所有改动,pull下了最新代码.还是开启主节点没问题,开启挖矿就不行

**Comment by dongshuyan** [comment]
我也遇到了相同的问题，求解

**Comment by dongshuyan** [comment]
我解决问题了。感觉原因可能是由于监听的端口没有释放。我重新启动一下就好了。你可以试一下

**Comment by ChengOrangeJu** [comment]
@jiyilanzhou  请添加微信号“nebulasio”，留言申请加入官方微信技术群：）目前已经有很多个群啦

**Comment by cyysu** [comment]
这个问题解决方案如下：
./neb -c conf/default/config.conf 
./neb -c conf/example/miner.conf 

不要忘记添加-c这个参数，希望可以帮到大家
