### ISSUE TITLE
无法使用 测试网和主网的admin api ？

### ISSUE THREAD

**Issue by DanisFabric** [nebulasio/wiki#94]
![2018-05-07 3 18 41](https://user-images.githubusercontent.com/7201854/39689654-2fb2cd6e-520a-11e8-980f-66eae35fcfd9.png)
用curl访问本地节点的admin api没问题，但是无法访问测试节点的admin api。是做过限制么？

**Comment by 0o8o0** [comment]
同问，请问你们解决了吗？
@DanisFabric @Dearkano

**Comment by ChengOrangeJu** [comment]
Admin endpoint is not support on mainnet for safety reason

**Comment by DanisFabric** [comment]
不能远程调用了，只有调用neb.js的函数 @Dearkano @0o8o0
