### ISSUE TITLE
删除数据库和neb项目后,重新按第一张顺序编辑,启动节点报错Failed to setup net service

### ISSUE THREAD

**Issue by jiyilanzhou** [nebulasio/wiki#96]
INFO[2018-05-07T18:43:58+08:00] Started crash reporter.                       file=crashclient.go func=main.InitCrashReporter line=115
ERRO[2018-05-07T18:43:58+08:00] Failed to start pprof                         err="<nil>" file=main.go func=main.runNeb line=103 listen="0.0.0.0:8888"
INFO[2018-05-07T18:43:58+08:00] Setuping Neblet...                            file=neblet.go func="neblet.(*Neblet).Setup" line=110
ERRO[2018-05-07T18:43:58+08:00] Failed to check port.                         err="listen port is not available" file=net_service.go func=net.NewNebService line=38 listen="[0.0.0.0:8680]"
FATA[2018-05-07T18:43:58+08:00] Failed to setup net service.                  err="listen port is not available" file=main.go func=main.runNeb line=108

**Comment by ChengOrangeJu** [comment]
it seems there is another process running on the same port. Try to use netstate -patn | grep yourport to find out which process and stop it xD
