### ISSUE TITLE
https://testnet.nebulas.io/claim/ does't work

### ISSUE THREAD

**Issue by momoko8443** [nebulasio/wiki#97]
Hi guys
I follow the solution of #92, then request 10 NAS on testnet by URL (https://testnet.nebulas.io/claim/#), but it doesn't work.  I even can't track the trade by the txhash. Could you help to check it....
I have to say I've got a low user experience on NEBULAS today...

**Comment by wangmaodong** [comment]
TxReceipt Status always in pending status
